trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python37:
      python.version: '3.7'
    Python38:
      python.version: '3.8'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    pip install mypy
    cd src
    mypy -p ty_cli
  displayName: 'mypy check'

- script: |
    pip --disable-pip-version-check install -U tox
    tox  -s false -- --junitxml=test-results.xml tests
  displayName: 'Run tox'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: test-results.xml
    testRunTitle: $(Agent.JobName)
  condition: eq(variables['hasTestResults'], 'true')
  displayName: Publish test results

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: coverage.xml
  condition: eq(variables['hasTestResults'], 'true')
  displayName: Publish coverage results
